/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.meia.project1;

import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mau_l
 */
public class Donaciones extends javax.swing.JFrame {

    /**
     * Creates new form Donaciones
     */
    
    String UsuarioBuscado = "";
    String NameBuscado = "";
    String FechaBuscado = "";
    
    String[] Buscado = new String[9];
    
    Archivo H = new Archivo();
    public Donaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        FechaField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SearchBtn = new javax.swing.JButton();
        PesoField = new javax.swing.JTextField();
        DescriptionField = new javax.swing.JTextField();
        EventField = new javax.swing.JTextField();
        UsuarioTField = new javax.swing.JTextField();
        FechaCreacionLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EditBtn = new javax.swing.JButton();
        EliminarBtn = new javax.swing.JButton();
        AlertLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario");

        jLabel2.setText("Nombre del material");

        jLabel3.setText("Fecha");

        SearchBtn.setText("Buscar");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Peso");

        jLabel5.setText("Descripcion");

        jLabel6.setText("Event");

        jLabel7.setText("Usuario de transaccion");

        EditBtn.setText("Modificacion");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        EliminarBtn.setText("Eliminar");
        EliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Puede realizar un cambio a la vez");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(UserField, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addComponent(NameField)
                                .addComponent(FechaField))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(SearchBtn)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(PesoField, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                        .addComponent(DescriptionField)
                                        .addComponent(EventField))
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(EditBtn)))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EliminarBtn)
                                    .addComponent(jLabel7)
                                    .addComponent(UsuarioTField, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(FechaCreacionLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AlertLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jLabel8))
                .addGap(0, 63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaCreacionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FechaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EventField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AlertLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBtn)
                    .addComponent(EditBtn)
                    .addComponent(EliminarBtn))
                .addGap(18, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        if(UserField.getText().equals("")){
            AlertLbl.setText("Debe ingresar el usuario que desea buscar");
        }
        else{
            AlertLbl.setText("");
            
            String Busqueda = "";
            
            if(FechaField.getText().equals("") && NameField.getText().equals("")){
                try {
                    List<String> L = H.Buscar(UserField.getText());
                    for (String x : L) {
                        Busqueda = x;
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Donaciones.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(FechaField.getText().equals("")){
                try {
                    List<String> L = H.Buscar(UserField.getText(), NameField.getText());
                    for (String x : L) {
                        Busqueda = x;
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Donaciones.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                try {
                    List<String> L = H.Buscar(UserField.getText(), NameField.getText(), FechaField.getText());
                    for (String x : L) {
                        Busqueda = x;
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Donaciones.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            String[] Splitsito = new String[9];
            Splitsito = Busqueda.split("\\|");
            
            if(!Busqueda.equals("404")){
                AlertLbl.setText("Registro Encontrado Existosamente");
                
                UserField.setText(Splitsito[0]);
                NameField.setText(Splitsito[1]);
                FechaField.setText(Splitsito[2]);
                PesoField.setText(Splitsito[3]);
                DescriptionField.setText(Splitsito[4]);
                EventField.setText(Splitsito[5]);
                UsuarioTField.setText(Splitsito[6]);
                FechaCreacionLbl.setText("Fecha de creacion:" + Splitsito[7]);
                
                UsuarioBuscado = Splitsito[0];
                NameBuscado = Splitsito[1];
                FechaBuscado = Splitsito[2];
                Buscado = Splitsito;
            }
            else
                AlertLbl.setText("No se encontro ningun registro");
            
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        if(UsuarioBuscado.equals("") || NameBuscado.equals("") || FechaBuscado.equals("")){
            AlertLbl.setText("Debe realizar busqueda");
        }
        else{
            String[] Aux = new String[7];
            Aux[0] = UserField.getText();
            Aux[1] = NameField.getText();
            Aux[2] = FechaField.getText();
            Aux[3] = PesoField.getText();
            Aux[4] = DescriptionField.getText();
            Aux[5] = EventField.getText();
            Aux[6] = UsuarioTField.getText();
            
            
            for (int i = 0; i < 7; i++) {
                System.out.println(i);
                if(!Buscado[i].equals(Aux[i])){
                    
                    try {
                        H.Actualizar(UsuarioBuscado, NameBuscado, FechaBuscado, i, Aux[i]);
                    } catch (IOException ex) {
                        Logger.getLogger(Donaciones.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            AlertLbl.setText("Actualizado debe volver a buscar para modificar");
        }
    }//GEN-LAST:event_EditBtnActionPerformed

    private void EliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtnActionPerformed
        if(UserField.getText().equals("")){
            AlertLbl.setText("Debe ingresar el usuario que desea buscar");
        }
        else{
            AlertLbl.setText("");
            
            Boolean Eliminado = false;
            
            if(!FechaField.getText().equals("") && !NameField.getText().equals("") && !UserField.getText().equals("")){
                try {
                    Eliminado = H.Eliminar(UserField.getText(), NameField.getText(), FechaField.getText());
                } catch (IOException ex) {
                    Logger.getLogger(Donaciones.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            
            if(Eliminado){
                AlertLbl.setText("Registro Eliminado Existosamente");
            }
            else
                AlertLbl.setText("Registro No Eliminado ");
            
        }
    }//GEN-LAST:event_EliminarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Donaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Donaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Donaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlertLbl;
    private javax.swing.JTextField DescriptionField;
    private javax.swing.JButton EditBtn;
    private javax.swing.JButton EliminarBtn;
    private javax.swing.JTextField EventField;
    private javax.swing.JLabel FechaCreacionLbl;
    private javax.swing.JTextField FechaField;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField PesoField;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField UserField;
    private javax.swing.JTextField UsuarioTField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
