/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.meia.project1;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mau_l
 */
public class Materiales extends javax.swing.JFrame {
    BinTree ABB = new BinTree();
    int Contador = 0;
    /**
     * Creates new form Materiales
     */
    public Materiales() {
        initComponents();
        try {
            ABB.Cargar();
        } catch(IOException ex) { ex.printStackTrace(); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IngresarBtn = new javax.swing.JButton();
        SearchBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        ElimiBtn = new javax.swing.JButton();
        MaterialBuscarField = new javax.swing.JTextField();
        NombreField = new javax.swing.JTextField();
        TipoField = new javax.swing.JTextField();
        TempoField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FechaLbl = new javax.swing.JLabel();
        UsuarioLbl = new javax.swing.JLabel();
        ImagBtn = new javax.swing.JButton();
        PathField = new javax.swing.JTextField();
        AlertLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        IngresarBtn.setText("Ingresar nuevo");
        IngresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarBtnActionPerformed(evt);
            }
        });

        SearchBtn.setText("Buscar");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        EditBtn.setText("Modificar");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        ElimiBtn.setText("Eliminar");
        ElimiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElimiBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre del material");

        jLabel2.setText("Tipo");

        jLabel3.setText("Tiempo para degradarse");

        ImagBtn.setText("Buscar imagen");
        ImagBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImagBtnActionPerformed(evt);
            }
        });

        PathField.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ElimiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MaterialBuscarField)
                            .addComponent(EditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(AlertLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TempoField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TipoField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IngresarBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ImagBtn)
                            .addComponent(FechaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UsuarioLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PathField))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(FechaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(UsuarioLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TempoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(PathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngresarBtn)
                    .addComponent(ImagBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchBtn)
                            .addComponent(MaterialBuscarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ElimiBtn)
                            .addComponent(EditBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(AlertLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String pathDescMateriales = "C:\\MEIA\\desc_Materiales.txt";                                 
        String pathMateriales = "C:\\MEIA\\Materiales.txt";
        
        File descMateriales = new File(pathDescMateriales);
        File Materiales = new File(pathMateriales);
        
        
    }//GEN-LAST:event_formWindowOpened

    private void ManejoArchivoArbol() {
        Contador++;
        String Nombre_Material = NombreField.getText();
        String tipo = TipoField.getText();
        String path = PathField.getText();
        String Tiempo_degradarse = TempoField.getText();
        String Usuario = ObtenerAdmin();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
        String FechaCreacion = sdf.format(new Date());
        String Status = "1";

        var todosLosRegistros = Nombre_Material + "|" + tipo + "|" + path + "|" + Tiempo_degradarse + "|" + Usuario + "|"
                + FechaCreacion + "|" + Status;

        ABB.Insertar(Nombre_Material, todosLosRegistros);

        try {
            ABB.WriteTree("C:\\MEIA\\Materiales_2.txt");
        } catch (IOException ex) { ex.printStackTrace(); }
    }
    
    private void IngresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarBtnActionPerformed
        // Ingresar nuevo material
        String Nombre_Material = NombreField.getText();
        String Tipo = TipoField.getText();
        String path = PathField.getText();
        String Tiempo_degradarse = TempoField.getText();
        String Usuario = ObtenerAdmin();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
        String FechaCreacion = sdf.format(new Date());
        String Status = "1";
        ManejoArchivoArbol();
        
        if(!Nombre_Material.equals("") && !Tipo.equals("") && !path.equals("") && !Tiempo_degradarse.equals("")){
            //Crear usuario
            //Crea trama de Nombre_Material|Tipo|Path_imagen
            String Material = Nombre_Material + "|" + Tipo + "|" + path;
            //Crea trama de |Tipo_para_degradarse|Usuario_Transaccion|fecha_Creacion
            Material += "|" + Tiempo_degradarse + "|" + Usuario + "|" + FechaCreacion;
            //Crea trama de |Status
            Material += "|" + Status;
            
            //Arreglo Dinamico leer bitacora
            int contador =0;
            File file = new File("C:\\MEIA\\Materiales.txt");
            if (file.exists()) {
                FileReader reader;
                try {
                    reader = new FileReader(file);
                    String linea;
                    BufferedReader bReader = new BufferedReader(reader);
                    while((linea=bReader.readLine())!=null){
                        contador++;
                    }

                    reader.close();
                    bReader.close();

                }catch (IOException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            String[] ListUsers = ReturnContent("Materiales", contador);

            //Escribir en bitacora
            FileWriter fichero = null;
            PrintWriter pw = null;
            try
            {
                fichero = new FileWriter("C:\\MEIA\\Materiales.txt");
                pw = new PrintWriter(fichero);
                for(int i = 0; i < contador; i++){
                    pw.println(ListUsers[i]);
                }
                pw.println(Material);

                fichero.close();
                pw.close(); 
                Retornar_vacio();
                AlertLbl.setText("Ingresado correctamente");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_IngresarBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        if(MaterialBuscarField.getText().equals("")){
            AlertLbl.setText("Debe ingresar el material que desea buscar");
        }
        else{
            AlertLbl.setText("");
            String linea = Buscar(ObtenerAdmin(), MaterialBuscarField.getText());
            String[] Material = new String[7];
            Material = linea.split("\\|");
            
            NombreField.setText(Material[0]);
            TipoField.setText(Material[1]);
            TempoField.setText(Material[3]);
            UsuarioLbl.setText(Material[4]);
            FechaLbl.setText(Material[5]);
            
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void ElimiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElimiBtnActionPerformed
        if(MaterialBuscarField.getText().equals("") || NombreField.getText().equals("") || TipoField.getText().equals("") || TempoField.getText().equals("")){
            AlertLbl.setText("Debe Buscar el material antes de Eliminar");
        }
        else{
            AlertLbl.setText("");
            String linea_material = Buscar(ObtenerAdmin(), MaterialBuscarField.getText());
            
            //Arreglo Dinamico leer bitacora
            int contador =0;
            File file = new File("C:\\MEIA\\Materiales.txt");
            if (file.exists()) {
                FileReader reader;
                try {
                    reader = new FileReader(file);
                    String linea;
                    BufferedReader bReader = new BufferedReader(reader);
                    while((linea=bReader.readLine())!=null){
                        contador++;
                    }

                    reader.close();
                    bReader.close();

                }catch (IOException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            String[] ListUsers = ReturnContent("Materiales", contador);

            //Escribir en bitacora
            FileWriter fichero = null;
            PrintWriter pw = null;
            try
            {
                fichero = new FileWriter("C:\\MEIA\\Materiales.txt");
                pw = new PrintWriter(fichero);
                for(int i = 0; i < contador; i++){
                    if(ListUsers[i].equals(linea_material))
                        continue;
                    else
                        pw.println(ListUsers[i]);
                }

                fichero.close();
                pw.close();                                                
            } catch (Exception e) {
                e.printStackTrace();
            }
            Retornar_vacio();
            AlertLbl.setText("Eliminar correctamente");
        }
    }//GEN-LAST:event_ElimiBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        if(MaterialBuscarField.getText().equals("") || NombreField.getText().equals("") || TipoField.getText().equals("") || TempoField.getText().equals("")){
            AlertLbl.setText("Debe Buscar el material antes de modificar");
        }
        else{
            AlertLbl.setText("");
            String linea_material = Buscar(ObtenerAdmin(), MaterialBuscarField.getText());
            String linea_original = linea_material;
            String[] Material = new String[7];
            Material = linea_material.split("\\|");
            
            Material[0] = NombreField.getText();
            Material[1] = TipoField.getText();
            Material[3] = TempoField.getText();
            
            linea_material = "";
            for (int i = 0; i < 7; i++) {
                if(i == 0)
                    linea_material += Material[0];
                else
                    linea_material += "|" + Material[i];
            }
            
            //Arreglo Dinamico leer bitacora
            int contador =0;
            File file = new File("C:\\MEIA\\Materiales.txt");
            if (file.exists()) {
                FileReader reader;
                try {
                    reader = new FileReader(file);
                    String linea;
                    BufferedReader bReader = new BufferedReader(reader);
                    while((linea=bReader.readLine())!=null){
                        contador++;
                    }

                    reader.close();
                    bReader.close();

                }catch (IOException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            String[] ListUsers = ReturnContent("Materiales", contador);

            //Escribir en bitacora
            FileWriter fichero = null;
            PrintWriter pw = null;
            try
            {
                fichero = new FileWriter("C:\\MEIA\\Materiales.txt");
                pw = new PrintWriter(fichero);
                for(int i = 0; i < contador; i++){
                    if(ListUsers[i].equals(linea_original))
                        pw.println(linea_material);
                    else
                        pw.println(ListUsers[i]);
                }

                fichero.close();
                pw.close();                                                
            } catch (Exception e) {
                e.printStackTrace();
            }
            Retornar_vacio();
            AlertLbl.setText("Editado correctamente");
        }
    }//GEN-LAST:event_EditBtnActionPerformed

    private void ImagBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImagBtnActionPerformed
        String[] formats = new String[] { "png", "jpg", "jpeg", "tiff", "ico", "bmp" };
        JFileChooser fChooser = new JFileChooser();
        FileNameExtensionFilter fnFilter = new FileNameExtensionFilter("Imagen", formats);
        File imageFile;
        fChooser.setFileFilter(fnFilter);
        int dialog = fChooser.showOpenDialog(this);
        
        if (dialog == JFileChooser.APPROVE_OPTION) {
            imageFile = fChooser.getSelectedFile();
            PathField.setText(imageFile.getPath());
        }
    }//GEN-LAST:event_ImagBtnActionPerformed

    public void Retornar_vacio (){
        NombreField.setText("");
        TipoField.setText("");
        TempoField.setText("");
        UsuarioLbl.setText("");
        FechaLbl.setText("");
        MaterialBuscarField.setText("");
    }
    
    public String Buscar(String Usuario, String NombreMaterial){
        File file = new File("C:\\MEIA\\Materiales.txt");
        String Retornar = "";
        if (file.exists()) {
            FileReader reader;
            try {
                reader = new FileReader(file);
                String linea;
                BufferedReader bReader = new BufferedReader(reader);
                while((linea=bReader.readLine())!=null){
                    String[] Material = new String[7];
                    Material = linea.split("\\|");
                    if(Material[0].equals(NombreMaterial) && Usuario.equals(Material[4])){
                        Retornar = linea;
                        break;
                    }
                }

                reader.close();
                bReader.close();
            }catch (IOException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return Retornar;
    }
    
    public String[] ReturnContent(String Archivo, int length){
        File file = new File("C:\\MEIA\\" + Archivo + ".txt");
        
        if (file.exists()) {
            FileReader reader;
            try {
                reader = new FileReader(file);
                BufferedReader bReader = new BufferedReader(reader);
                
                String linea;
                String[] retornar = new String[length];
                int i = 0;
                while((linea=bReader.readLine())!=null){
                    retornar[i] = linea;
                    i++;
                }
                reader.close();
                bReader.close();
                return retornar;
            }catch (IOException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        return null;
    }
    
    public String ObtenerAdmin(){
        File file = new File("C:\\MEIA\\bitacora_usuario.txt");
        if (file.exists()) {
            FileReader reader;
            try {
                reader = new FileReader(file);
                BufferedReader bReader = new BufferedReader(reader);
                Boolean ExisteAdmin = false;
                String linea;//Usada para leer linea por linea los usuarios
                while((linea=bReader.readLine())!=null){
                    String[] Usuario = new String[10];
                    Usuario = linea.split("\\|");
                    if(Usuario[4].equals("1")){
                        return Usuario[0];
                    }
                }
                reader.close();
                bReader.close();
            }catch (IOException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        file = new File("C:\\MEIA\\usuario.txt");
        if (file.exists()) {
            FileReader reader;
            try {
                reader = new FileReader(file);
                BufferedReader bReader = new BufferedReader(reader);
                Boolean ExisteAdmin = false;
                String linea;//Usada para leer linea por linea los usuarios
                while((linea=bReader.readLine())!=null){
                    String[] Usuario = new String[10];
                    Usuario = linea.split("\\|");
                    if(Usuario[4].equals("1")){
                        return Usuario[0];
                    }
                }
                reader.close();
                bReader.close();
            }catch (IOException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Materiales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlertLbl;
    private javax.swing.JButton EditBtn;
    private javax.swing.JButton ElimiBtn;
    private javax.swing.JLabel FechaLbl;
    private javax.swing.JButton ImagBtn;
    private javax.swing.JButton IngresarBtn;
    private javax.swing.JTextField MaterialBuscarField;
    private javax.swing.JTextField NombreField;
    private javax.swing.JTextField PathField;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField TempoField;
    private javax.swing.JTextField TipoField;
    private javax.swing.JLabel UsuarioLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
