/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.meia.project1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Stream;

/**
 *
 * @author mau_l
 */
public class RecycleDashboard extends javax.swing.JFrame {

    /**
     * Creates new form RecycleDashboard
     */
    public RecycleDashboard(String user) {
        User = user;
        initComponents();
    }
    Archivo H = new Archivo();
    String User = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PesoField = new javax.swing.JTextField();
        RecyBtn = new javax.swing.JButton();
        FechaField = new javax.swing.JTextField();
        DescriptionField = new javax.swing.JTextField();
        EventField = new javax.swing.JTextField();
        UsuarioField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AlertLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MaterialesField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PesoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PesoFieldKeyPressed(evt);
            }
        });

        RecyBtn.setText("Donar");
        RecyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecyBtnActionPerformed(evt);
            }
        });

        FechaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Material");

        jLabel2.setText("Fecha");

        jLabel3.setText("Peso");

        jLabel4.setText("Descripcion");

        jLabel5.setText("Evento");

        jLabel6.setText("Usuario de transaccion");

        jLabel7.setText("Materiales Validos");

        jLabel8.setText("jLabel8");

        MaterialesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaterialesFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(RecyBtn)
                    .addComponent(FechaField, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(PesoField, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(MaterialesField))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DescriptionField)
                    .addComponent(EventField)
                    .addComponent(UsuarioField)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AlertLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addGap(65, 65, 65)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DescriptionField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(MaterialesField))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(FechaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PesoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EventField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6)
                        .addGap(1, 1, 1)
                        .addComponent(UsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(AlertLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RecyBtn)))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PesoFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PesoFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesoFieldKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        System.out.println("Se abrio");
        try {
            H.Inicializar(ObtenerAdmin());
            int contador =0;
            File file = new File("C:\\MEIA\\bitacora_usuario.txt");
            if (file.exists()) {
                FileReader reader;
                try {
                    reader = new FileReader(file);
                    String linea;
                    BufferedReader bReader = new BufferedReader(reader);
                while((linea=bReader.readLine())!=null){
                    contador++;
                }
                reader.close();
                bReader.close();
                }catch (IOException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            String[] Materiales = ReturnContent("", contador);
            String MaterialesView = "<html>";
            for (int i = 0; i < contador; i++) {
                if(Materiales[i] == null){
                    continue;
                }
                String[] Spliteado = Materiales[i].split("\\|");
                MaterialesView += Spliteado[0];
                MaterialesView += "<br/>";
            }
            jLabel8.setText(MaterialesView);
        } catch (IOException ex) {
            Logger.getLogger(RecycleDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void RecyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecyBtnActionPerformed
        int contador =0;
        File file = new File("C:\\MEIA\\bitacora_usuario.txt");
        if (file.exists()) {
            FileReader reader;
            try {
                reader = new FileReader(file);
                String linea;
                BufferedReader bReader = new BufferedReader(reader);
            while((linea=bReader.readLine())!=null){
                contador++;
            }
            reader.close();
            bReader.close();
            }catch (IOException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        String[] Materiales = ReturnContent("", contador);
        boolean MaterialValido = false;
        for (int i = 0; i < contador++; i++) {
            String[] Spliteado = Materiales[i].split("\\|");
            System.out.println(Spliteado[0]);
            System.out.println(MaterialesField.getText());
            if (Spliteado[0].equals(MaterialesField.getText())) {
                
                MaterialValido = true;
                break;
            }
        }
        
        

        //Donar
        if(PesoField.getText().equals("") || FechaField.getText().equals("") || EventField.getText().equals("") || 
                DescriptionField.getText().equals("") || UsuarioField.getText().equals("") || !MaterialValido){
            AlertLbl.setText("Tiene que ingresar todos los campos");
        }
        else{
            try {
                H.Insertar(User, FechaField.getText(), MaterialesField.getText(), Integer.parseInt(PesoField.getText()), DescriptionField.getText(), EventField.getText(), UsuarioField.getText());
                AlertLbl.setText("Donado");
            } catch (IOException ex) {
                Logger.getLogger(RecycleDashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_RecyBtnActionPerformed

    public String[] ReturnContent(String Archivo, int length){
        File file = new File("C:\\MEIA\\Materiales.txt");
        
        if (file.exists()) {
            FileReader reader;
            try {
                reader = new FileReader(file);
                BufferedReader bReader = new BufferedReader(reader);
                
                String linea;
                String[] retornar = new String[length];
                int i = 0;
                while((linea=bReader.readLine())!=null){
                    retornar[i] = linea;
                    i++;
                }
                reader.close();
                bReader.close();
                return retornar;
            }catch (IOException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        return null;
    }
    
    private void FechaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaFieldActionPerformed

    private void MaterialesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaterialesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaterialesFieldActionPerformed

    public String ObtenerAdmin(){
        File file = new File("C:\\MEIA\\bitacora_usuario.txt");
        if (file.exists()) {
            FileReader reader;
            try {
                reader = new FileReader(file);
                BufferedReader bReader = new BufferedReader(reader);
                Boolean ExisteAdmin = false;
                String linea;//Usada para leer linea por linea los usuarios
                while((linea=bReader.readLine())!=null){
                    String[] Usuario = new String[10];
                    Usuario = linea.split("\\|");
                    if(Usuario[4].equals("1")){
                        return Usuario[0];
                    }
                }
                reader.close();
                bReader.close();
            }catch (IOException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        file = new File("C:\\MEIA\\usuario.txt");
        if (file.exists()) {
            FileReader reader;
            try {
                reader = new FileReader(file);
                BufferedReader bReader = new BufferedReader(reader);
                Boolean ExisteAdmin = false;
                String linea;//Usada para leer linea por linea los usuarios
                while((linea=bReader.readLine())!=null){
                    String[] Usuario = new String[10];
                    Usuario = linea.split("\\|");
                    if(Usuario[4].equals("1")){
                        return Usuario[0];
                    }
                }
                reader.close();
                bReader.close();
            }catch (IOException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return null;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecycleDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecycleDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecycleDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecycleDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecycleDashboard("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlertLbl;
    private javax.swing.JTextField DescriptionField;
    private javax.swing.JTextField EventField;
    private javax.swing.JTextField FechaField;
    private javax.swing.JTextField MaterialesField;
    private javax.swing.JTextField PesoField;
    private javax.swing.JButton RecyBtn;
    private javax.swing.JTextField UsuarioField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
